#testing github actions env variables

name: Echo Git Variables

on:
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Command
        run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF
          echo $GITHUB_ENV