#testing github actions env variables

name: Echo Git Variables

on:
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Set Image Version
        if: ${{$GITHUB_REF_NAME == 'main'}}
        run: |
          echo PROD
          echo "DOCKER_IMAGE_VERSION=PROD >> $GITHUB_ENV"
          echo ${{env.DOCKER_IMAGE_VERSION}}